server.port: 8080
jwt:
  secretKey: fljfkowienfkdjiewof;sjdfopirjwnffsdjkewoirjwjlkfnadskfljsdlkfs

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9020
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
        - id: dataset-service
          uri: ${DATASET_SERVICE_URL:http://dataset-service:9030}
          predicates:
            - Path=/api/v1/datasets/**
management:
  endpoints:
    web:
      exposure:
        include: gateway,health
